import { StyleSheet } from "react-native";
import { COLORS } from "../../../../../constants/colors";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: COLORS.primaryOpacity,
    },
    modal: {
        width: "90%",
        padding: 24,
        borderWidth: 2,
        borderRadius: 16,
        borderColor: COLORS.terciary,
        backgroundColor: COLORS.primary,
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    headerTitle: {
        paddingTop: 10,
        position: "absolute",
        paddingLeft: 5,
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: "center",
        color: COLORS.terciary,
        left: 0,
        right: 0,
        paddingBottom: 5,
        paddingHorizontal: 5,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.terciary,
    },
    closeBtn: {},
    stars: {
        paddingTop: 20,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center"
    },
    title: {
        marginLeft: 5,
        marginTop: 15,
        color: COLORS.terciary,
    },
    input: {
        padding: 12,
        marginTop: 5,
        borderWidth: 1,
        borderRadius: 8,
        marginBottom: 15,
        flexDirection: "row",
        alignItems: "center",
        color: COLORS.terciary,
        borderColor: COLORS.terciary,
    },
    inputText: {
        marginLeft: 8,
        color: COLORS.terciary,
    },
    multiline: {
        height: 200,
        padding: 12,
        marginTop: 5,
        borderWidth: 1,
        borderRadius: 8,
        marginBottom: 15,
        flexDirection: "row",
        alignItems: "center",
        color: COLORS.terciary,
        textAlignVertical: "top",
        borderColor: COLORS.terciary,
    },
    form: {
        marginBottom: 10,
        flexDirection: "row",
        alignItems: "center"
    },
    checkbox: {
        marginLeft: 2,
        borderRadius: 5,
    },
    inputTagView: {
        padding: 12,
        marginTop: 5,
        borderWidth: 1,
        borderRadius: 8,
        marginBottom: 10,
        flexDirection: "row",
        color: COLORS.terciary,
        alignItems: "flex-start",
        justifyContent: "space-between",
        borderColor: COLORS.terciary,
    },
    inputTag: {
        color: COLORS.terciary,
    },
    tags: {
        maxWidth: "85%",
        flexDirection: "row",
        alignItems: "flex-start",
    },
    tagsHeader: {
        flexDirection: "row",
        alignItems: "center",
    },
    text: {
        fontSize: 15,
        marginRight: 5,
        color: COLORS.secondary,
    },
    list: {
        marginRight: 5,
        flexWrap: "wrap", 
        flexDirection: "row",
        alignItems: "flex-start",
    },
    tag: {
        padding: 3,
        marginLeft: 3,
        marginBottom: 3,
        borderWidth: 1,
        borderRadius: 5,
        borderColor: COLORS.secondary,
    },
    tagText: {
        flexShrink: 1,
        fontSize: 10,
        fontWeight: "bold",
        color: COLORS.secondary,
        textTransform: "uppercase",
    },
    btnView: {
        marginTop: 20,
        alignItems: "center",
    },
    btn: {
        width: 100,
        height: 30,
        borderRadius: 8,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: COLORS.secondary,
    },
    btnText: {
        fontWeight: "bold",
        textAlign: "center",
        color: COLORS.terciary,
    },
});