import { StyleSheet } from "react-native";

export const stylesheet = (theme: any) => StyleSheet.create({
    header: {
        width: '100%',
        paddingTop: 10,
        paddingBottom: 15,
        alignItems: 'center',
        flexDirection: 'row',
        paddingHorizontal: 20,
        justifyContent: 'space-between',
        backgroundColor: theme.primary,
    },
    headerItemLeft: {
        flex: 1,
    },
    headerItemRight: {
        flex: 1,
        alignItems: 'flex-end',
    },
    headerTitle: {
        fontSize: 20,
        lineHeight: 25,
        color: theme.terciary,
        fontFamily: 'IBMPlexMono_400Regular',
    },
    container: {
        flex: 1,
        borderRadius: 12,
        backgroundColor: theme.primary,
    },
    top: {
        width: '100%',
        paddingTop: 10,
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
    },
    review: {
        paddingLeft: 20,
        alignItems: "flex-start",
        justifyContent: "center",
    },
    info: {
        flex: 1,
        flexDirection: "column",
    },
    infoUser: {
        flexDirection: "row",
        alignItems: "center",
    },
    user: {
        fontSize: 20,
        paddingLeft: 5,
        fontWeight: 'bold',
        color: theme.terciary,
        fontFamily: 'IBMPlexMono_400Regular',
    },
    commenter: {
        fontSize: 12,
        paddingLeft: 5,
        fontWeight: 'bold',
        color: theme.terciary,
        fontFamily: 'IBMPlexMono_700Bold',
    },
    time: {
        fontSize: 10,
        paddingLeft: 10,
        color: theme.terciary,
        fontFamily: 'IBMPlexMono_400Regular',
    },
    aboutText: {
        padding: 5,
        fontSize: 10,
        fontWeight: 'bold',
        color: theme.terciary,
    },
    title: {
        padding: 5,
        fontSize: 18,
        marginTop: 10,
        marginRight: 25,
        fontWeight: "bold",
        textAlign: "justify",
        color: theme.terciary,
    },
    description: {
        padding: 5,
        fontSize: 15,
        marginRight: 25,
        textAlign: "justify",
        color: theme.terciary,
    },
    more: {
        fontSize: 12,
        fontWeight: 'bold',
        color: theme.terciary,
    },
    stars: {
        paddingLeft: 5,
        flexDirection: "row",
        alignItems: "center",
    },
    options: {
        width: "95%",
        paddingTop: 5,
        flexDirection: "row",
        alignItems: "flex-start",
        justifyContent: "space-between",
    },
    option: {
        flexDirection: "row",
        alignItems: "center",
    },
    rate: {
        fontSize: 10,
        paddingLeft: 5,
        color: theme.terciary,
    },
    divider: {
        margin: 5,
        height: 1,
        width: '92%',
        marginVertical: 10,
        backgroundColor: theme.terciary,
    },
    list: {
        flexDirection: "column",
    },
    comments: {
        marginBottom: 5,
        paddingLeft: 25,
        flexDirection: "row",
    },
    count: {
        fontSize: 15,
        paddingLeft: 5,
        color: theme.terciary,
    },
    comment: {
        padding: 10,
        borderWidth: 1,
        borderRadius: 15,
        marginVertical: 5,
        marginHorizontal: 20,
        borderColor: theme.terciary,
    },
    commentLike: {
        paddingTop: 5,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    bottom: {
        left: 0,
        right: 0,
        bottom: 0,
        padding: 15,
        borderRadius: 12,
        borderTopWidth: 1,
        flexDirection: 'row',
        alignItems: 'center',
        position: 'absolute',
        borderTopColor: theme.terciary,
        backgroundColor: theme.primary,
    },
    input: {
        flex: 1,
        padding: 15,
        maxHeight: 100,
        borderWidth: 1,
        borderRadius: 20,
        paddingVertical: 10,
        marginHorizontal: 15,
        color: theme.terciary,
        borderColor: theme.terciary,
    },
    btn: {
        marginHorizontal: 10,
    },
});