import { StyleSheet } from "react-native";

export const stylesheet = (theme: any) => StyleSheet.create({
    container: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: theme.primaryOpacity,
    },
    modal: {
        width: "90%",
        padding: 24,
        borderWidth: 2,
        borderRadius: 16,
        borderColor: theme.terciary,
        backgroundColor: theme.primary,
    },
    header: {
        marginBottom: 20,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    headerTitle: {
        left: 0,
        right: 0,
        fontSize: 20,
        paddingLeft: 5,
        paddingTop: 10,
        paddingBottom: 5,
        fontWeight: 'bold',
        textAlign: "center",
        position: "absolute",
        paddingHorizontal: 5,
        borderBottomWidth: 1,
        color: theme.terciary,
        borderBottomColor: theme.terciary,
        fontFamily: 'IBMPlexMono_400Regular',
    },
    title: {
        marginLeft: 5,
        marginVertical: 5,
        color: theme.terciary,
    },
    input: {
        padding: 12,
        borderWidth: 1,
        borderRadius: 8,
        marginBottom: 15,
        flexDirection: "row",
        alignItems: "center",
        color: theme.terciary,
        borderColor: theme.terciary,
    },
    inputText: {
        marginLeft: 8,
        color: theme.terciary,
    },
    password: {
        marginBottom: 20,
        flexDirection: "row",
        alignItems: "center",
    },
    eyeIcon: {
        top: 0,
        right: 5,
        bottom: 15,
        padding: 5,
        position: 'absolute',
        alignItems: 'center',
        justifyContent: 'center',
    },
    btnView: {
        alignItems: "center",
    },
    btn: {
        width: 100,
        height: 30,
        borderRadius: 8,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: theme.secondary,
    },
    btnText: {
        fontWeight: "bold",
        textAlign: "center",
        color: theme.terciary,
    },
});